default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default  
  database: invoice_app_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: invoice_app_test
  username: postgres
  password: password  
  host: localhost
  port: 5432      

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>